package order.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
// for purchasing an order user need to pass the following fields
public class OrderRequestDto {

    // validate the available amount in the payment service.
    private Integer userId;
    // which product you want to purchase.
    private Integer productId;
    // what's the amount for that particular product.
    private Integer amount;
    // autogenerated value through the system to trace the order.
    private Integer orderId;
}